### ISSUE TITLE
Throttle

### ISSUE THREAD

**Issue by QuillanFae** [hammond-of-texas/OldSchoolDialer#1]
Find the user's location after connection based on their IP. Look up their global internet speed ranking with something like the Trading Economics API. Apply a speed cap in the range of 14 - 128kbps based on that ranking.

**Comment by hammond-of-texas** [comment]
This sounds like a fun idea. Probably a bit more complicated to implement but I will look into this.

**Comment by hammond-of-texas** [comment]
Ok, added throttling the internet speed to 128 KBit/s as long as the application is running. It needs admin rights now to run. Tried different settings, but can't go lower than 128 KBit/s because otherwise many sites just time out.
